function p = dfd_dq_cartpole(th1_d,th2_d,th3_d,dth1_d,dth2_d,dth3_d,u2_d,u3_d,m1,m2,m3,l1,l2,l3,g)
%DFD_DQ_CARTPOLE
%    P = DFD_DQ_CARTPOLE(TH1_D,TH2_D,TH3_D,DTH1_D,DTH2_D,DTH3_D,U2_D,U3_D,M1,M2,M3,L1,L2,L3,G)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    20-Nov-2016 22:18:51

t2 = sin(th3_d);
t3 = cos(th3_d);
t4 = cos(th1_d);
t5 = sin(th1_d);
t6 = sin(th2_d);
t7 = l1.*l2.*t4.*t6.*2.0;
t8 = cos(th2_d);
t9 = t7-l1.*l2.*t5.*t8.*2.0;
t10 = th3_d.^2;
t11 = l3.*t3.*2.0;
t16 = l3.*t2.*th3_d;
t12 = t11-t16;
t13 = l3.*t2.*2.0;
t14 = l3.*t3.*th3_d;
t15 = t13+t14;
t17 = l1.*t4.*t12.*2.0;
t18 = l1.*t5.*t15.*2.0;
t19 = t17+t18;
t20 = dth1_d.*l1.*t4.*t12.*2.0;
t21 = dth1_d.*l1.*t5.*t15.*2.0;
t22 = t20+t21;
t23 = l3.*t2;
t24 = t14+t23;
t25 = l1.*t4.*t24.*2.0;
t28 = l3.*t3;
t32 = t16-t28;
t26 = l1.*t5.*t32.*2.0;
t27 = t25+t26;
t29 = l2.*t8.*t12.*2.0;
t30 = l2.*t6.*t15.*2.0;
t31 = t29+t30;
t33 = t16-l3.*t3.*3.0;
t34 = l3.*t2.*3.0;
t35 = t14+t34;
t36 = dth2_d.*l2.*t8.*t12.*2.0;
t37 = dth2_d.*l2.*t6.*t15.*2.0;
t38 = t36+t37;
t39 = l2.*t8.*t24.*2.0;
t40 = l2.*t6.*t32.*2.0;
t41 = t39+t40;
p = reshape([m2.*t10.*t19.*(1.0./4.0),dth1_d.*m2.*t9.*-2.0,-dth1_d.*(m2.*t27.*(1.0./2.0)+m2.*t19.*th3_d.*(1.0./4.0))-th3_d.*(m2.*t22.*(1.0./4.0)+m2.*th3_d.*(l1.*t4.*t33.*2.0-l1.*t5.*t35.*2.0).*(1.0./4.0)+dth1_d.*m2.*t19.*(1.0./4.0))-dth1_d.*m2.*t27.*(1.0./2.0)-m2.*t22.*th3_d.*(1.0./4.0),dth2_d.*m2.*t9.*2.0,m2.*t10.*t31.*(1.0./4.0),-dth2_d.*(m2.*t41.*(1.0./2.0)+m2.*t31.*th3_d.*(1.0./4.0))-th3_d.*(m2.*t38.*(1.0./4.0)-m2.*th3_d.*(l2.*t6.*t35.*2.0-l2.*t8.*t33.*2.0).*(1.0./4.0)+dth2_d.*m2.*t31.*(1.0./4.0))-dth2_d.*m2.*t41.*(1.0./2.0)-m2.*t38.*th3_d.*(1.0./4.0),0.0,0.0,0.0],[3,3]);
