function p = dfdu_cartpole(th1_d,th2_d,th3_d,dth1_d,dth2_d,dth3_d,u2_d,u3_d,m1,m2,m3,l1,l2,l3,g)
%DFDU_CARTPOLE
%    P = DFDU_CARTPOLE(TH1_D,TH2_D,TH3_D,DTH1_D,DTH2_D,DTH3_D,U2_D,U3_D,M1,M2,M3,L1,L2,L3,G)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    20-Nov-2016 22:18:51

p = reshape([0.0,1.0,0.0,0.0,0.0,1.0],[3,2]);
