function p = KE_3R(th1,th2,th3,dth1,dth2,dth3,m1,m2,m3,l1,l2,l3,u2,u3,g)
%KE_3R
%    P = KE_3R(TH1,TH2,TH3,DTH1,DTH2,DTH3,M1,M2,M3,L1,L2,L3,U2,U3,G)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    20-Nov-2016 22:18:48

t7 = sin(th1);
t12 = dth1.*l1.*t7;
t13 = sin(th2);
t14 = dth2.*l2.*t13;
t2 = t12+t14+l3.*th3.*sin(th3);
t4 = cos(th1);
t8 = dth1.*l1.*t4;
t9 = cos(th2);
t10 = dth2.*l2.*t9;
t3 = t8+t10+l3.*th3.*cos(th3);
t5 = dth1.^2;
t6 = l1.^2;
t11 = t8+t10;
t15 = t12+t14;
p = m1.*(t4.^2.*t5.*t6+t5.*t6.*t7.^2).*(1.0./2.0)+m2.*(t2.^2+t3.^2).*(1.0./2.0)+m2.*(t11.^2+t15.^2).*(1.0./2.0);
