function p = M_3R(th1,th2,th3,dth1,dth2,dth3,m1,m2,m3,l1,l2,l3,u2,u3,g)
%M_3R
%    P = M_3R(TH1,TH2,TH3,DTH1,DTH2,DTH3,M1,M2,M3,L1,L2,L3,U2,U3,G)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    20-Nov-2016 22:18:48

t2 = cos(th1);
t3 = l1.^2;
t4 = sin(th1);
t5 = t2.^2;
t6 = t3.*t5.*2.0;
t7 = t4.^2;
t8 = t3.*t7.*2.0;
t9 = t6+t8;
t10 = sin(th3);
t11 = cos(th3);
t12 = sin(th2);
t13 = l1.*l2.*t4.*t12.*2.0;
t14 = cos(th2);
t15 = l1.*l2.*t2.*t14.*2.0;
t16 = t13+t15;
t17 = m2.*t16;
t18 = l2.^2;
t19 = l3.*t11;
t24 = l3.*t10.*th3;
t20 = t19-t24;
t21 = l3.*t10;
t22 = l3.*t11.*th3;
t23 = t21+t22;
t25 = l1.*t2.*t20.*2.0;
t26 = l1.*t4.*t23.*2.0;
t27 = t25+t26;
t28 = m2.*t27.*(1.0./2.0);
t29 = l2.*t14.*t20.*2.0;
t30 = l2.*t12.*t23.*2.0;
t31 = t29+t30;
t32 = m2.*t31.*(1.0./2.0);
p = reshape([m1.*t9.*(1.0./2.0)+m2.*t9,t17,t28,t17,m2.*(t12.^2.*t18.*2.0+t14.^2.*t18.*2.0),t32,t28,t32,m2.*((t22+l3.*t10.*2.0).*(t22+dth1.*l1.*t2+dth2.*l2.*t14).*2.0+(t24-l3.*t11.*2.0).*(t24+dth1.*l1.*t4+dth2.*l2.*t12).*2.0-t20.^2.*2.0-t23.^2.*2.0).*(-1.0./2.0)],[3,3]);
