function p = P_mass2(th1,th2,th3,dth1,dth2,dth3,m1,m2,m3,l1,l2,l3,u2,u3,g)
%P_MASS2
%    P = P_MASS2(TH1,TH2,TH3,DTH1,DTH2,DTH3,M1,M2,M3,L1,L2,L3,U2,U3,G)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    20-Nov-2016 22:18:45

p = [l1.*sin(th1)+l2.*sin(th2);l1.*cos(th1)+l2.*cos(th2)];
