function p = PE_3R(th1,th2,th3,dth1,dth2,dth3,m1,m2,m3,l1,l2,l3,u2,u3,g)
%PE_3R
%    P = PE_3R(TH1,TH2,TH3,DTH1,DTH2,DTH3,M1,M2,M3,L1,L2,L3,U2,U3,G)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    20-Nov-2016 22:18:48

t2 = cos(th1);
t3 = l1.*t2;
t4 = cos(th2);
t5 = l2.*t4;
p = g.*m3.*(t3+t5+l3.*cos(th3))+g.*m2.*(t3+t5)+g.*l1.*m1.*t2;
